# Generated by Django 3.0.6 on 2020-06-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200618_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
    ]
