# Generated by Django 3.0.6 on 2020-06-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200618_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuser',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='groupuser',
            old_name='user',
            new_name='user_id',
        ),
    ]
