# Generated by Django 3.0.6 on 2020-06-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.TextField(verbose_name='Dados'),
        ),
    ]
