# Generated by Django 3.0.7 on 2020-06-19 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_Municipio', models.CharField(max_length=5, verbose_name='Códigos  Municípios')),
                ('Nome', models.CharField(max_length=60, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=120, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=120, verbose_name='Nome Fantasia')),
                ('CNPJ', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='I.E')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, verbose_name='I.M')),
                ('numero_CNAE', models.IntegerField(verbose_name='Numero CNAE')),
                ('logradouro', models.CharField(blank=True, max_length=120, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('CEP', models.IntegerField(max_length=8, verbose_name='CEP')),
                ('UF', models.CharField(max_length=2, verbose_name='UF')),
                ('complemento', models.CharField(max_length=250, verbose_name='Complemento')),
                ('diretor_geral', models.CharField(max_length=120, verbose_name='Diretor Geral')),
                ('diretor_administrativo', models.CharField(max_length=120, verbose_name='Diretor Administrativo')),
                ('diretor_financeiro', models.CharField(max_length=120, verbose_name='Diretor Financeiro')),
                ('telefone_emergencia', models.IntegerField(max_length=11, verbose_name='Fone Emergencia: ')),
                ('ramal_emergencia', models.IntegerField(max_length=11, verbose_name='Ramal Emergência')),
                ('celular_emergencia', models.IntegerField(max_length=11, verbose_name='Celular Emergência')),
                ('telefone_ambulatorio', models.IntegerField(max_length=11, verbose_name='Celular Emergência')),
                ('ramal_ambulatorio', models.IntegerField(max_length=11, verbose_name='Ramal Ambulatório')),
                ('celular_ambulatorio', models.IntegerField(max_length=11, verbose_name='Celular Ambulatório')),
                ('telefone_centro_cirurgico', models.IntegerField(max_length=11, verbose_name='Tel. Centro Cirúrgico')),
                ('ram_centro_cirurgico', models.IntegerField(max_length=11, verbose_name='Ramal C. Cirúrgico')),
                ('celular_centro_cirurgico', models.IntegerField(max_length=11, verbose_name='Celular C. Cirúrgico')),
                ('telefone_geral', models.IntegerField(max_length=11, verbose_name='Telefone Geral')),
                ('celular_geral', models.IntegerField(max_length=11, verbose_name='Celular Geral')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='status')),
                ('municipios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='System.Municipios')),
            ],
        ),
    ]
