# Generated by Django 3.0.7 on 2020-06-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicoes',
            name='celular_ambulatorio',
            field=models.CharField(max_length=11, verbose_name='Celular Ambulatório'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='celular_centro_cirurgico',
            field=models.CharField(max_length=11, verbose_name='Celular C. Cirúrgico'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='celular_emergencia',
            field=models.CharField(max_length=11, verbose_name='Celular Emergência'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='celular_geral',
            field=models.CharField(max_length=11, verbose_name='Celular Geral'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='ram_centro_cirurgico',
            field=models.CharField(max_length=11, verbose_name='Ramal C. Cirúrgico'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='ramal_ambulatorio',
            field=models.CharField(max_length=11, verbose_name='Ramal Ambulatório'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='ramal_emergencia',
            field=models.CharField(max_length=11, verbose_name='Ramal Emergência'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='telefone_ambulatorio',
            field=models.CharField(max_length=11, verbose_name='Celular Emergência'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='telefone_centro_cirurgico',
            field=models.CharField(max_length=11, verbose_name='Tel. Centro Cirúrgico'),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='telefone_emergencia',
            field=models.CharField(max_length=11, verbose_name='Fone Emergencia: '),
        ),
        migrations.AlterField(
            model_name='instituicoes',
            name='telefone_geral',
            field=models.CharField(max_length=11, verbose_name='Telefone Geral'),
        ),
    ]
