# Generated by Django 3.0.7 on 2020-06-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_auto_20200619_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicoes',
            name='CEP',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
    ]
