# Generated by Django 3.0.7 on 2020-06-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_auto_20200619_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipios',
            name='UF',
            field=models.CharField(default='CE', max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
    ]
